POST http://localhost:3000/api/auth/reset-password 
Content-Type: application/json
    
{
    "email": "nikitakuzmenko1107@gmail.com"
}

###

PATCH http://localhost:3000/api/auth/reset-password/confirm
Content-Type: application/json

{
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im5pa2l0YWt1em1lbmtvMTEwN0BnbWFpbC5jb20iLCJyZXNldFBhc3N3b3JkIjp0cnVlLCJpYXQiOjE2ODE3NDg5OTcsImV4cCI6MTY4NDM0MDk5N30.qO1Cf0jDVmQ51As5PJBcPZYAhkxNXB83KQ9wt4HuD4s",
    "password": "12345"
}